version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo apt-get update
      - sudo apt-get install -y nginx

  build:
    commands:
      - echo "Build started on $(date)"
      - sudo cp index.html /var/www/html/
      - sudo cp home.html /var/www/html/
      - sudo cp contact.html /var/www/html/
      - sudo cp style.css /var/www/html/
      - sudo cp contact.css /var/www/html/
      - sudo cp app.js /var/www/html/

  post_build:
    commands:
      - echo "Configuring NGINX"
      - sudo systemctl restart nginx || true

artifacts:
  files:
    - '**/*'
